<!DOCTYPE html>
<html lang="id">

<head>
    <title>Laporan_<?= $data['month_name']; ?>_<?= $data['year']; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
    /* CSS Khusus Cetak */
    body {
        font-family: 'Times New Roman', serif;
        color: #000;
    }

    .header-laporan {
        border-bottom: 3px double #000;
        margin-bottom: 20px;
        padding-bottom: 10px;
    }

    .ttd-area {
        margin-top: 50px;
        text-align: right;
    }

    @media print {
        .no-print {
            display: none !important;
        }

        /* Hilangkan tombol saat print */
        body {
            margin: 0;
            padding: 0;
        }
    }
    </style>
</head>

<body onload="window.print()">
    <div class="container mt-4">

        <button class="btn btn-secondary no-print mb-3" onclick="window.close()">
            &larr; Tutup Preview
        </button>

        <div class="header-laporan text-center">
            <h2 class="fw-bold text-uppercase">Laporan Keuangan Pribadi</h2>
            <h5>Periode: <?= $data['month_name']; ?> <?= $data['year']; ?></h5>
            <small>Dicetak otomatis oleh Sistem MyMoney</small>
        </div>

        <div class="row mb-4">
            <div class="col-6">
                <strong>Nama Pemilik:</strong> <?= $data['user']; ?><br>
                <strong>Tanggal Cetak:</strong> <?= date('d F Y'); ?>
            </div>
            <div class="col-6 text-end">
                <strong>Status:</strong> Generated by System
            </div>
        </div>

        <table class="table table-bordered table-sm border-dark">
            <thead class="table-light border-dark text-center">
                <tr>
                    <th>No</th>
                    <th>Tanggal</th>
                    <th>Kategori</th>
                    <th>Keterangan</th>
                    <th>Masuk (IDR)</th>
                    <th>Keluar (IDR)</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                $no = 1;
                $totalMasuk = 0;
                $totalKeluar = 0;
                ?>

                <?php if(empty($data['transactions'])) : ?>
                <tr>
                    <td colspan="6" class="text-center">Tidak ada transaksi bulan ini.</td>
                </tr>
                <?php else : ?>
                <?php foreach($data['transactions'] as $trx) : ?>
                <?php 
                            $isIncome = $trx['type'] == 'income';
                            if($isIncome) $totalMasuk += $trx['amount'];
                            else $totalKeluar += $trx['amount'];
                        ?>
                <tr>
                    <td class="text-center"><?= $no++; ?></td>
                    <td class="text-center"><?= date('d/m/Y', strtotime($trx['transaction_date'])); ?></td>
                    <td><?= $trx['category_name']; ?></td>
                    <td><?= $trx['description']; ?></td>
                    <td class="text-end"><?= $isIncome ? number_format($trx['amount'], 0, ',', '.') : '-'; ?></td>
                    <td class="text-end"><?= !$isIncome ? number_format($trx['amount'], 0, ',', '.') : '-'; ?></td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
            <tfoot class="fw-bold border-dark">
                <tr class="table-light">
                    <td colspan="4" class="text-center">TOTAL</td>
                    <td class="text-end text-success">Rp <?= number_format($totalMasuk, 0, ',', '.'); ?></td>
                    <td class="text-end text-danger">Rp <?= number_format($totalKeluar, 0, ',', '.'); ?></td>
                </tr>
                <tr>
                    <td colspan="4" class="text-center">SISA SALDO (Cashflow)</td>
                    <td colspan="2" class="text-center bg-light">
                        Rp <?= number_format($totalMasuk - $totalKeluar, 0, ',', '.'); ?>
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="ttd-area">
            <p>Karawang, <?= date('d F Y'); ?></p>
            <p>Mengetahui,</p>
            <br><br><br>
            <p class="fw-bold text-decoration-underline"><?= $data['user']; ?></p>
            <small>( Pemilik Akun )</small>
        </div>

    </div>

</body>

</html>